# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: MotionPDX - Portland RubyMotion Meetup
description: >
  We are a group of RubyMotion enthusiasts. We enjoy building mobile apps with
  RubyMotion and want to share our knowledge with the rest of the community.
  Join us for presentations, demos, discussions, and help getting started with
  RubyMotion.
url: "https://motionpdx.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title/
